---
title: Student Union
timezone: UTC
collections:
  merchandise:
    title: Merchandise
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: studentunion@rbs.lv
description: 'The Riga Business School Student Union stands for the interests of all
  RBS students. We build a community of leaders who leave a positive impact on society.

'
url: studentunion.co
twitter_username: twitter_username
github_username: github_username
markdown: kramdown
highlighter: rouge
baseurl: 
paginate: 15
paginate_path: "/blog/page:num/"
